from src.backtesting.trade import TradeManager
from src.backtesting.performance_calculator import BacktestPerformance

class BacktestController:
    def __init__(self):
        self.trade_manager = TradeManager()
        self.engine = None

    def allin(self, engine: BacktestEngine):
        """
        Executes a backtest for all selected strategies, trading all signals without any position sizing or risk management.

        This method runs the backtest engine, then iterates through all generated trading signals. For each signal, it attempts to execute a trade. If the trade is successful, it prints a message indicating the trade action and the remaining cash balance. If the trade fails, it prints a message indicating the failed trade action and the remaining cash balance.

        Args:
            engine (BacktestEngine): The backtest engine instance to run the backtest with.
        """
        self.engine = engine
        self.engine.run()
        print("check")
        # Execute all trading signals generated by the backtest
        for signals in self.engine.signals:
            for signal in signals:
                # Directly use the attributes of the ordersignal object
                if signal.action == 'BUY':
                    buy_success = self.trade_manager.buy(signal.price, self.trade_manager.cash / signal.price)
                    if buy_success:
                        print(f"BUY: {signal}, remaining cash: {self.trade_manager.cash}")
                    else:
                        print(f"Void Buy: {signal}, remaining cash: {self.trade_manager.cash}")
                elif signal.action == 'SELL':
                    sell_success = self.trade_manager.sell(signal.price, self.trade_manager.current_quantity)
                    if sell_success:
                        print(f"SELL: {signal}")
                    else:
                        print(f"Void Sell: {signal}")

    def fix_pos_limit_exp(self, engine: BacktestEngine, fix_pos_limit_percentage: float = 1.0, max_exposure: float = 1.0):
        """
        Run a backtest for selected strategies with max exposure and fix position limit.

        This method runs the backtest engine, then iterates through all generated trading signals. For each signal, it attempts to execute a trade. If the trade is successful, it adds the trade to a list of buy orders. If the trade fails, it prints a message indicating the failed trade action and the remaining cash balance.

        Args:
            engine (BacktestEngine): The backtest engine instance to run the backtest with.
            fix_pos_limit_percentage (float, optional): The percentage of the initial capital to use as the fix position limit. Defaults to 1.0.
            max_exposure (float, optional): The percentage of the initial capital to use as the max exposure. Defaults to 1.0.
        """
        self.engine = engine
        self.engine.run()
        # Trade all signals in the backtest
        fix_pos_limit_capital = self.trade_manager.initial_capital * fix_pos_limit_percentage
        max_exposure_capital = self.trade_manager.initial_capital * max_exposure
        buy_orders = []
        for signals in self.engine.signals:
            for signal in signals:
                if signal.action == 'BUY' and (self.trade_manager.initial_capital - self.trade_manager.cash > max_exposure_capital):
                    buy_success = self.trade_manager.buy(signal.price, fix_pos_limit_capital / signal.price)
                    if buy_success:                    
                        # Assuming trade_manager.trades holds the recent trade, as a replacement for positions
                        buy_orders.append(self.trade_manager.trades[-1])
                elif signal.action == 'SELL':
                    if buy_orders:
                        self.trade_manager.sell(signal.price, buy_orders.pop(-1).position)

    def get_result(self):
        """
        Retrieves the results of the backtest, organized by strategy.

        Returns:
            dict: A dictionary where each key is a strategy name and the value is another dictionary containing the trade signals for that strategy. If no strategies are defined, returns all trades under a generic key.

        Raises:
            ValueError: If no trades were executed during the backtest.
        """
        if self.trade_manager.get_trade_count() > 0:
            # If the engine holds strategies and signals, group the signals by strategy.
            if self.engine and hasattr(self.engine, "strategies") and len(self.engine.signals) == len(self.engine.strategies):
                results_by_strategy = {}
                for strategy, signals in zip(self.engine.strategies, self.engine.signals):
                    # Use a 'name' attribute if available, otherwise default to the class name.
                    strategy_name = getattr(strategy, "name", strategy.__class__.__name__)
                    results_by_strategy[strategy_name] = {"signals": signals}
                return results_by_strategy
            else:
                # Fallback: return all trades under a generic key.
                return {"All Trades": {"signals": self.trade_manager.get_trades()}}
        else:
            raise ValueError("No trades executed.")
    
    def get_updated_equity_curve(self):
        """
        Retrieves the updated equity curve based on the trades executed during the backtest.

        Returns:
            list: A list of equity values, starting with the initial capital and followed by the capital after each trade.
        """
        equity_curve = [self.trade_manager.initial_capital]
        for trade in self.trade_manager.get_trades():
            equity_curve.append(trade.capital)
        return equity_curve

    def get_performance(self):
        """
        Calculates and prints the backtest performance metrics using the updated equity curve and trade returns.

        This method first constructs the equity curve from the trade manager's executed trades. Then, it computes trade returns as the percentage change in equity from one trade to the next. Finally, it calculates and prints various performance metrics, including the Sharpe ratio, Sortino ratio, Calmar ratio, and others, using a 2% annual risk-free rate.
        """
        # Retrieve the equity curve, which includes the initial capital and the capital after each trade.
        equity_curve = self.get_updated_equity_curve()
        
        # Calculate trade returns based on the change in equity after each trade.
        trade_returns = []
        for i in range(1, len(equity_curve)):
            previous = equity_curve[i - 1]
            current = equity_curve[i]
            # Ensure division by zero is avoided (although unlikely with a nonzero initial capital)
            trade_return = (current - previous) / previous if previous != 0 else 0.0
            trade_returns.append(trade_return)
        
        # Utilize a 2% annual risk-free rate for performance calculations
        calc = BacktestPerformance(risk_free_rate=0.02)
        performance_result = calc.calculate(equity_curve, trade_returns)
        
        print(performance_result)